---
   # requires staging of a config file
   - name: "Install Qpid"
     shell: /opt/apigee/apigee-setup/bin/setup.sh -p qs -f /opt/apigee/configFile

   - name: "Restart"
     command:  '/opt/apigee/apigee-service/bin/apigee-all restart'
     
   - name: "Enable autostart"
     command:  '/opt/apigee/apigee-service/bin/apigee-all enable_autostart'
     
     
