---
- name: 'Prepare for Apigee Install - Primary'
  hosts: postgres-portal-pri
  serial: 1
  become: yes
  become_user: "root"
  roles:
      - ../../roles/apigee-base
      - ../../roles/apigee-config
      - ../../roles/apigee-postgres_portal
      
- name: 'Prepare for Apigee Install - Secondary'
  hosts: postgres-portal-sec
  serial: 1
  become: yes
  become_user: "root"
  roles:
      - ../../roles/apigee-base
      - ../../roles/apigee-config
      - ../../roles/apigee-postgres_portal
     
     
