---
# tasks file for apigeeService
#
#
- name: Download the bootstrap script from apigee site
  get_url:
         url: https://software.apigee.com/bootstrap_4.17.09.sh
         dest: /tmp/bootstrap.sh
         mode: 0755
         owner: root
         group: root

- name: Get stats about /opt/apigee/apigee-service
  stat: 
      path: /opt/apigee/apigee-service
  register: serviceStatus
   
- name: Execute bootstrap script
  shell: bash /tmp/bootstrap.sh apigeeuser={{ ftpSiteUser }} apigeepassword={{ ftpSitePass }}
  register: result
  become: true
  become_method: su
  become_user: root
  when: serviceStatus.stat.exists == False

#- debug: 
#       msg: Status of bootstrap script executions is {{ result.stdout }}

- name: Install the apigee Setup utility
  shell: /opt/apigee/apigee-service/bin/apigee-service apigee-setup install
  when: serviceStatus.stat.exists == False

- name: Create link for log directory
  file:
      src: '/opt/apigee/var/log/'
      dest: '/var/log/apigee'
      state: link
      force: yes

     
