---
# Validate management-server, edge ui  processes is not running on the nodes

    - name: Check Edge UI Process status
      shell: /opt/apigee/apigee-service/bin/apigee-service edge-ui status
      ignore_errors: true
      register: edgeUI_status

    - name: Debug
      debug:
          msg: "{{ edgeUI_status.stderr }}"

    - name: Notify failure
      fail:
        msg: "APIGEE EDGE-UI HAS STOPPED ON {{ inventory_hostname }} SERVER"
      when: '"apigee-service: edge-ui: Not running" not in edgeUI_status.stderr'

    - name: Check Edge Management Server status
      shell: /opt/apigee/apigee-service/bin/apigee-service edge-management-server status
      ignore_errors: true
      register: status

    - name: Debug
      debug:
          msg: "{{ status.stderr }}"

    - name: Notify failure
      fail:
        msg: "APIGEE MGT HAS STOPPED ON {{ inventory_hostname }} SERVER"
      when: '"apigee-service: edge-management-server: Not running" not in status.stderr'
