---
  # Requires Restore QPID  processes
  - stat:
    path: /opt/apigee/backup
    register: result
  - debug:
    msg: "Backup Directory exists"
    when: result.stat.exists

  - name: Clean up Directories and Files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /opt/apigee/backup
      - /opt/apigee/etc/qpid.d
      - /opt/apigee/etc/qpid-server.d

  - name: "Restore apigee-qpidd"
    shell: /opt/apigee/apigee-service/bin/apigee-service apigee-qpidd restore backup-2019.**.**,**.**.**.tar.gz

  - name: "Restore  edge-qpid-server"
    shell: /opt/apigee/apigee-service/bin/apigee-service edge-qpid-server restore backup-2019.**.**,**.**.**.tar.gz