---
  # Requires Restore Devportal processes
  - stat:
    path: /opt/apigee/backup
    register: result
  - debug:
    msg: "Backup Directory exists"
    when: result.stat.exists

  - name: Clean up Directories and Files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /opt/apigee/backup
      - /opt/apigee/etc/devportal.d
      - /opt/apigee/etc/drupal.d
      - /opt/apigee/etc/lb.d

  - name: "Restore apigee-drupal"
    shell: /opt/apigee/apigee-service/bin/apigee-service apigee-drupal restore backup-2019.**.**,**.**.**.tar.gz

  - name: "Restore apigee-drupal-devportal"
    shell: /opt/apigee/apigee-service/bin/apigee-service apigee-drupal-devportal restore backup-2019.**.**,**.**.**.tar.gz

  - name: "Restore apigee-lb"
    shell: /opt/apigee/apigee-service/bin/apigee-service apigee-lb restore backup-2019.**.**,**.**.**.tar.gz