- hosts: '{{ env }}-{{ dc }}-zooKeeper-cassandra'
  roles: 
       - preConfigs
       - java
       - apigeeService
       - zooKeeper_cassandra

- hosts: '{{ env }}-{{ dc }}-managementServer-edgeUI'
  roles:
       - preConfigs
       - java
       - apigeeService
       - managementServer_edgeUI


- hosts: '{{ env }}-{{ dc }}-router-messageProcessor'
  roles:
       - preConfigs
       - java
       - apigeeService
       - router_messageProcessor

- hosts: '{{ env }}-{{ dc }}-openLDAP'
  roles:
       - preConfigs
       - java
       - apigeeService
       - openLDAP

- hosts: '{{ env }}-{{ dc }}-qpidServer'
  roles:
       - preConfigs
       - java
       - apigeeService
       - qpidServer

- hosts: '{{ env }}-{{ dc }}-postgresServer'
  roles:
       - preConfigs
       - java
       - apigeeService
       - postgresServer

- hosts: '{{ env }}-{{ dc }}-devPortalDB'
  roles:
       - preConfigs
       - java
       - apigeeService
       - devPortalDB

- hosts: '{{ env }}-{{ dc }}-devPortal'
  roles:
       - preConfigs
       - java
       - apigeeService
       - devPortal

- hosts: '{{ env }}'
  roles:
       - autoRestartScripts
