---
# Apigee base
   - name: Clear staging area
     become: no
     run_once: yes
     local_action:
       module: shell rm -Rf apigee-configuration
       
   - name: Acquire the configuration files from GIT
     become: no
     run_once: yes
     local_action: 
       module: git
       repo: git@repo.west.com:Systems-and-Platforms/apigee-configuration.git
       dest: "./apigee-configuration"
       force: yes

   # requires a reboot
   - name: Disable SElinux 
     selinux:
       state: disabled
       policy: permissive
       
   # requires a reboot
   - name: Disable IPv6 with sysctl
     sysctl: name={{ item }} value=1 state=present
     with_items:
       - net.ipv6.conf.all.disable_ipv6
       - net.ipv6.conf.default.disable_ipv6
       - net.ipv6.conf.lo.disable_ipv6
       
   - name: Stop firewall
     service:
       name: firewalld
       state: stopped
       enabled: False
       
   - name: Stop NSCD
     ignore_errors: yes
     service:
       name: nscd
       state: stopped
       enabled: False

   - name: yum-clean-metadata
     command: yum clean metadata
     args:
       warn: no
     

   - name: Ensures /opt/apigee Exists
     file: path=/opt/apigee state=directory
          
   - name: Stage this server's apigee license file
     copy:
       src: apigee-configuration/license/license.txt
       dest: /opt/apigee/license.txt
       owner: "{{ service_account }}"
       group: "{{ service_group }}"
       mode: 0644

   - name: Create the /etc/security/limits.d/90-apigee-edge-limits.conf file
     copy:
       src: apigee-configuration/tmpl/90-apigee-edge-limits.conf
       dest: /etc/security/limits.d/90-apigee-edge-limits.conf
       owner: root
       group: root
       mode: 0644
       
   - name: Add EPEL Repository
     yum_repository:
       name: epel
       description: EPEL YUM repo
       file: external_repos
       baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
       gpgcheck: no

# local apigee repo install
   - name: Add Apigee Release Repository
     yum_repository:
       name: apigee-release
       description: Apigee Release Repo
       file: apigee_internal
       baseurl: "{{ rpm_repo }}/{{ apigee_ver }}/apigee-release/"
       gpgcheck: no

# local apigee repo install
   - name: Add Apigee Third Party Components Repository
     yum_repository:
       name: apigee-thirdparty
       description: Apigee Third Party Components Repository 
       file: apigee_internal
       baseurl: "{{ rpm_repo }}/{{ apigee_ver }}/apigee-thirdparty/"
       gpgcheck: no
    
   - name: "Install OpenJDK"
     yum:
       name: 'java'
       state: latest
    
   - name: "Install apigee-service"
     yum:
       name: 'apigee-service'
       state: latest
    
   - name: "Install apigee-setup"
     command:  '/opt/apigee/apigee-service/bin/apigee-service apigee-setup install'
     
