---
# Validate devportal processes is not running on the nodes

    - name: Check Devportal process status
      shell: /opt/apigee/apigee-service/bin/apigee-service apigee-drupal-devportal status 
      ignore_errors: true
      register: devportal_status

    - name: Debug
      debug:
        msg: "{{ devportal_status.stdout }}"

    - name: Notify failure
      fail:
          msg: "APIGEE DEVPORTAL HAS STOPPED ON {{ inventory_hostname }} SERVER"
      when: '"apigee-drupal-devportal is not running" not in devportal_status.stdout'

    - name: Check Apigee load balancer process status
      shell: /opt/apigee/apigee-service/bin/apigee-service apigee-lb status
      ignore_errors: true
      register: apigee_lb_status

    - name: Debug
      debug:
        msg: "{{ apigee_lb_status.stderr }}"

    - name: Notify failure
      fail:
          msg: "APIGEE LOADBALANCER SERVER HAS STOPPED ON {{ inventory_hostname }} SERVER"
      when: '"apigee-service: apigee-lb: Not running" not in apigee_lb_status.stderr'