---
   # requires staging of a config file
   - name: "Install edge-management-server"
     shell: /opt/apigee/apigee-setup/bin/setup.sh -p ms -f /opt/apigee/configFile
     
   - name: Copy this server's jks files
     copy:
       src: certs/keystore.jks
       dest: /opt/apigee/customer/application/keystore.jks
       owner: "{{ service_account }}"
       group: "{{ service_group }}"
       mode: 0644
       
   - name: Copy this server's ui ssl files
     copy:
       src: config/edgeui-ssl.config
       dest: /opt/apigee/customer/application/edgeui-ssl.config
       owner: "{{ service_account }}"
       group: "{{ service_group }}"
       mode: 0644

   - name: Copy this server's management ssl files
     copy:
       src: config/management-server.properties
       dest: /opt/apigee/customer/application/management-server.properties
       owner: "{{ service_account }}"
       group: "{{ service_group }}"
       mode: 0644

   - name: Copy this server's ui ssl files
     copy:
       src: config/ui.properties
       dest: /opt/apigee/customer/application/ui.properties
       owner: "{{ service_account }}"
       group: "{{ service_group }}"
       mode: 0644

   - name: "Enable SSL"
     command:  '/opt/apigee/apigee-service/bin/apigee-service edge-ui configure-ssl -f /opt/apigee/customer/application/edgeui-ssl.config'

   - name: "Restart"
     command:  '/opt/apigee/apigee-service/bin/apigee-all restart'
     
   - name: "Enable autostart"
     command:  '/opt/apigee/apigee-service/bin/apigee-all enable_autostart'
     
     
