---
# Components Installation validation in Zookeeper and cassandra nodes
    - name: Check Cassandra process status
      shell: /opt/apigee/apigee-service/bin/apigee-service apigee-cassandra status
      register: cassandra_status

    - name: Debug
      debug:
          msg: "{{ cassandra_status.stderr }}"

    - name: Notify failure
      fail:
        msg: "APIGEE CASSANDRA HAS NOT STARTED ON {{ inventory_hostname }} SERVER"
      when: '"apigee-service: apigee-cassandra: OK" not in cassandra_status.stderr'   

    - name: Check Zookeeper process status
      shell: /opt/apigee/apigee-service/bin/apigee-service apigee-zookeeper status
      register: zookeeper_status

    - name: Debug
      debug:
          msg: "{{ zookeeper_status.stderr }}"

    - name: Notify failure
      fail:
        msg: "APIGEE ZOOKEEPER HAS NOT STARTED ON {{ inventory_hostname }} SERVER"
      when: '"apigee-service: apigee-zookeeper: OK" not in zookeeper_status.stderr'

# Port 2181 validation for other components requests to Zookeeper

    - name: Check open port 2181 on zookeeper server1 on SWN01 for requests from other components
      shell: nc -vz 10.65.188.23 2181
      register: zk11_port_2181

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 2181 ON 10.65.188.23 SERVER"
      when: '"Connected to 10.65.188.23:2181" not in zk11_port_2181.stderr'

    - name: Check open port 2181 on zookeeper server2 SWN01 for requests from other components
      shell: nc -vz 10.65.188.24 2181
      register: zk12_port_2181

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 2181 ON 10.65.188.24 SERVER"
      when: '"Connected to 10.65.188.24:2181" not in zk12_port_2181.stderr'

    - name: Check open port 2181 on zookeeper server3 SWN01 for requests from other components
      shell: nc -vz 10.65.188.25 2181
      register: zk13_port_2181

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 2181 ON 10.65.188.25 SERVER"
      when: '"Connected to 10.65.188.25:2181" not in zk13_port_2181.stderr'

    - name: Check open port 2181 on zookeeper server1 DEN06 for requests from other components
      shell: nc -vz 10.71.178.23 2181
      register: zk21_port_2181

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 2181 ON 10.71.178.23 SERVER"
      when: '"Connected to 10.71.178.23:2181" not in zk21_port_2181.stderr'

    - name: Check open port 2181 on zookeeper server2 DEN06 for requests from other components
      shell: nc -vz 10.71.178.24 2181
      register: zk22_port_2181

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 2181 ON 10.71.178.24 SERVER"
      when: '"Connected to 10.71.178.24:2181" not in zk22_port_2181.stderr'

    - name: Check open port 2181 on zookeeper server3 DEN06 for requests from other components
      shell: nc -vz 10.71.178.25 2181
      register: zk23_port_2181

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 2181 ON 10.71.178.25 SERVER"
      when: '"Connected to 10.71.178.25:2181" not in zk23_port_2181.stderr'

# Port 3888 validation for internal zookeeper to Zookeeper

    - name: Check open port 3888 on zookeeper server1 on SWN01 for zookeeper cluster
      shell: nc -vz 10.65.188.23 3888
      register: zk11_port_3888

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 3888 ON 10.65.188.23 SERVER"
      when: '"Connected to 10.65.188.23:3888" not in zk11_port_3888.stderr'

    - name: Check open port 3888 on zookeeper server2 SWN01 for zookeeper cluster
      shell: nc -vz 10.65.188.24 3888
      register: zk12_port_3888

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 3888 ON 10.65.188.24 SERVER"
      when: '"Connected to 10.65.188.24:3888" not in zk12_port_3888.stderr'

    - name: Check open port 3888 on zookeeper server3 SWN01 for zookeeper cluster
      shell: nc -vz 10.65.188.25 3888
      register: zk13_port_3888

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 3888 ON 10.65.188.25 SERVER"
      when: '"Connected to 10.65.188.25:3888" not in zk13_port_3888.stderr'

    - name: Check open port 3888 on zookeeper server1 DEN06 for zookeeper cluster
      shell: nc -vz 10.71.178.23 3888
      register: zk21_port_3888

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 3888 ON 10.71.178.23 SERVER"
      when: '"Connected to 10.71.178.23:3888" not in zk21_port_3888.stderr'

    - name: Check open port 3888 on zookeeper server2 DEN06 for zookeeper cluster
      shell: nc -vz 10.71.178.24 3888
      register: zk22_port_3888

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 3888 ON 10.71.178.24 SERVER"
      when: '"Connected to 10.71.178.24:3888" not in zk22_port_3888.stderr'

    - name: Check open port 3888 on zookeeper server3 DEN06 for zookeeper cluster
      shell: nc -vz 10.71.178.25 3888
      register: zk23_port_3888

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 3888 ON 10.71.178.25 SERVER"
      when: '"Connected to 10.71.178.25:3888" not in zk23_port_3888.stderr'

# Apache Cassandra Port 7000 validation for communication between cassandra nodes

    - name: Check open port 7000 on cassandra server1 on SWN01 for communication between cassandra nodes
      shell: nc -vz 10.65.188.23 7000
      register: cass11_port_7000

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 7000 ON 10.65.188.23 SERVER"
      when: '"Connected to 10.65.188.23:7000" not in cass11_port_7000.stderr'

    - name: Check open port 7000 on cassandra server2 SWN01 for communication between cassandra nodes
      shell: nc -vz 10.65.188.24 7000
      register: cass12_port_7000

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 7000 ON 10.65.188.24 SERVER"
      when: '"Connected to 10.65.188.24:7000" not in cass12_port_7000.stderr'

    - name: Check open port 7000 on cassandra server3 SWN01 for communication between cassandra nodes
      shell: nc -vz 10.65.188.25 7000
      register: cass13_port_7000

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 7000 ON 10.65.188.25 SERVER"
      when: '"Connected to 10.65.188.25:7000" not in cass13_port_7000.stderr'

    - name: Check open port 7000 on cassandra server1 DEN06 for communication between cassandra nodes
      shell: nc -vz 10.71.178.23 7000
      register: cass21_port_7000

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 7000 ON 10.71.178.23 SERVER"
      when: '"Connected to 10.71.178.23:7000" not in cass21_port_7000.stderr'

    - name: Check open port 7000 on cassandra server2 DEN06 for communication between cassandra nodes
      shell: nc -vz 10.71.178.24 7000
      register: cass22_port_7000

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 7000 ON 10.71.178.24 SERVER"
      when: '"Connected to 10.71.178.24:7000" not in cass22_port_7000.stderr'

    - name: Check open port 7000 on cassandra server3 DEN06 for communication between cassandra nodes
      shell: nc -vz 10.71.178.25 7000
      register: cass23_port_7000

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 7000 ON 10.71.178.25 SERVER"
      when: '"Connected to 10.71.178.25:7000" not in cass23_port_7000.stderr'

# Apache Cassandra Port 9042 validation for communication between cassandra nodes

    - name: Check open port 9042 on cassandra server1 on SWN01 for communication between cassandra nodes
      shell: nc -vz 10.65.188.23 9042
      register: cass11_port_9042

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 9042 ON 10.65.188.23 SERVER"
      when: '"Connected to 10.65.188.23:9042" not in cass11_port_9042.stderr'

    - name: Check open port 9042 on cassandra server2 SWN01 for communication between cassandra nodes
      shell: nc -vz 10.65.188.24 9042
      register: cass12_port_9042

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 9042 ON 10.65.188.24 SERVER"
      when: '"Connected to 10.65.188.24:9042" not in cass12_port_9042.stderr'

    - name: Check open port 9042 on cassandra server3 SWN01 for communication between cassandra nodes
      shell: nc -vz 10.65.188.25 9042
      register: cass13_port_9042

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 9042 ON 10.65.188.25 SERVER"
      when: '"Connected to 10.65.188.25:9042" not in cass13_port_9042.stderr'

    - name: Check open port 9042 on cassandra server1 DEN06 for communication between cassandra nodes
      shell: nc -vz 10.71.178.23 9042
      register: cass21_port_9042

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 9042 ON 10.71.178.23 SERVER"
      when: '"Connected to 10.71.178.23:9042" not in cass21_port_9042.stderr'

    - name: Check open port 9042 on cassandra server2 DEN06 for communication between cassandra nodes
      shell: nc -vz 10.71.178.24 9042
      register: cass22_port_9042

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 9042 ON 10.71.178.24 SERVER"
      when: '"Connected to 10.71.178.24:9042" not in cass22_port_9042.stderr'

    - name: Check open port 9042 on cassandra server3 DEN06 for communication between cassandra nodes
      shell: nc -vz 10.71.178.25 9042
      register: cass23_port_9042

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 9042 ON 10.71.178.25 SERVER"
      when: '"Connected to 10.71.178.25:9042" not in cass23_port_9042.stderr'

# Apache Cassandra Port 9160 validation for communication between cassandra nodes

    - name: Check open port 9160 on cassandra server1 on SWN01 for communication between cassandra nodes
      shell: nc -vz 10.65.188.23 9160
      register: cass11_port_9160

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 9160 ON 10.65.188.23 SERVER"
      when: '"Connected to 10.65.188.23:9160" not in cass11_port_9160.stderr'

    - name: Check open port 9160 on cassandra server2 SWN01 for communication between cassandra nodes
      shell: nc -vz 10.65.188.24 9160
      register: cass12_port_9160

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 9160 ON 10.65.188.24 SERVER"
      when: '"Connected to 10.65.188.24:9160" not in cass12_port_9160.stderr'

    - name: Check open port 9160 on cassandra server3 SWN01 for communication between cassandra nodes
      shell: nc -vz 10.65.188.25 9160
      register: cass13_port_9160

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 9160 ON 10.65.188.25 SERVER"
      when: '"Connected to 10.65.188.25:9160" not in cass13_port_9160.stderr'

    - name: Check open port 9160 on cassandra server1 DEN06 for communication between cassandra nodes
      shell: nc -vz 10.71.178.23 9160
      register: cass21_port_9160

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 9160 ON 10.71.178.23 SERVER"
      when: '"Connected to 10.71.178.23:9160" not in cass21_port_9160.stderr'

    - name: Check open port 9160 on cassandra server2 DEN06 for communication between cassandra nodes
      shell: nc -vz 10.71.178.24 9160
      register: cass22_port_9160

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 9160 ON 10.71.178.24 SERVER"
      when: '"Connected to 10.71.178.24:9160" not in cass22_port_9160.stderr'

    - name: Check open port 9160 on cassandra server3 DEN06 for communication between cassandra nodes
      shell: nc -vz 10.71.178.25 9160
      register: cass23_port_9160

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 9160 ON 10.71.178.25 SERVER"
      when: '"Connected to 10.71.178.25:9160" not in cass23_port_9160.stderr'