---
# tasks file for preConfigs
#

- name: Install git module 
  yum:
     name: git
     state: present

- name: Get all the packages from Gitlab
  git:
     repo: eitgitlp@gitlab.west.com:IVR_Engineering/apigeePackages.git
     dest: "{{ gitDownloadPath }}"
     accept_hostkey: yes
     force: yes

- name: Set permission on downloaded repository
  file:
      path: "{{ gitDownloadPath }}"
      state: directory
      owner: root
      group: root
      recurse: yes

- name: Get all usr/local/bin files from Gitlab
  git:
     repo: eitgitlp@gitlab.west.com:IVR_Engineering/usrLocalBinPackage.git
     dest: "{{ gitDownloadPath }}/bin/"
     accept_hostkey: yes
     force: yes

- name: Set permission on downloaded usr/local/bin repository
  file:
      path: "{{ gitDownloadPath }}/bin"
      state: directory
      owner: root
      group: root
      mode: 0755
      recurse: yes

- name: Copy usr/local/bin files from downloaded repository
  synchronize:
             src: "{{ gitDownloadPath }}/bin/"
             dest: /usr/local/bin/
  delegate_to: "{{ inventory_hostname }}"

- name: Disable SElinux 
  selinux:
         state: disabled 
  become: true
  become_method: su
  become_user: root

- name: Install EPEL repository
  yum:
     name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
     state: present

- name: Stop firewall demon
  command: systemctl stop firewalld
  become: true
  become_method: su
  become_user: root


- name: Disable firewall demon 
  command: systemctl disable firewalld
  become: true
  become_method: su
  become_user: root

- name: Change the permission 
  file: 
      path: /etc/rc.d/init.d/functions
      mode: 0744
      owner: root
      group: root

- name: Copy configFile 
  copy:
      src: '{{ gitDownloadPath }}/configFile-{{ env }}-{{ dc }}'
      dest: '{{ configFilePath }}'
      mode: 0755
      remote_src: true
 
- name: Copy license file 
  copy:
      src: '{{ gitDownloadPath }}/license.txt'
      dest: '{{ licenseFilePath }}'
      mode: 0755 
      remote_src: true 
