---
  # Requires Restore Messege processor and message router  processes
  - stat:
    path: /opt/apigee/backup
    register: result
  - debug:
    msg: "Backup Directory exists"
    when: result.stat.exists

  - name: Clean up Directories and Files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /opt/apigee/backup
      - /opt/apigee/etc/router.d
      - /opt/apigee/etc/processor.d

  - name: "Restore edge-message-processor"
    shell: /opt/apigee/apigee-service/bin/apigee-service edge-message-processor restore backup-2019.**.**,**.**.**.tar.gz

  - name: "Restore  edge-router"
    shell: /opt/apigee/apigee-service/bin/apigee-service edge-router restore backup-2019.**.**,**.**.**.tar.gz