---
   # Requires backup zookeeper and cassandra processes
   
   - name: "Backup  apigee-zookeeper"
     shell: /opt/apigee/apigee-service/bin/apigee-service apigee-zookeeper backup

   - name: Ensures /opt/apigee/backup/zookeeper Exists
     file: path=/opt/apigee/backup/zookeeper state=directory

   - name: "Backup  apigee-cassandra"
     shell: /opt/apigee/apigee-service/bin/apigee-service apigee-cassandra backup

   - name: Ensures /opt/apigee/backup/cassandra Exists
     file: path=/opt/apigee/backup/cassandra state=directory 
