---
# Components Installation validation in MR and MP nodes
    - name: Check Router process status
      shell: /opt/apigee/apigee-service/bin/apigee-service edge-router status 
      ignore_errors: true
      register: router_status

    - name: Debug
      debug:
        msg: "{{ router_status.stderr }}"

    - name: Notify failure
      fail:
          msg: "APIGEE MR HAS NOT STARTED ON {{ inventory_hostname }} SERVER"
      when: '"apigee-service: edge-router: OK" not in router_status.stderr'

    - name: Check Message-Processor process status
      shell: /opt/apigee/apigee-service/bin/apigee-service edge-message-processor status
      ignore_errors: true
      register: message_processor_status

    - name: Debug
      debug:
        msg: "{{ message_processor_status.stderr }}"

    - name: Notify failure
      fail:
          msg: "APIGEE MPR HAS NOT STARTED ON {{ inventory_hostname }} SERVER"
      when: '"apigee-service: edge-message-processor: OK" not in message_processor_status.stderr'

# Check servers response status for MR and MP

    - name: Check apigee servers response status for Router
      raw: "curl -I http://{{ inventory_hostname }}:8081/v1/servers/self/up"
      register: router_resp
     
    - name: Debug
      debug:
          msg: "{{ router_resp.stdout }}"
          
    - name: Notify failure
      fail:
        msg: "APIGEE MR ON SERVER {{ inventory_hostname }} IS UP AND REACHABLE"
      when: '"HTTP/1.1 200" not in router_resp.stdout'

    - name: Check apigee servers response status for Message Processor
      raw: "curl -I http://{{ inventory_hostname }}:8082/v1/servers/self/up"
      register: message_processor_resp
     
    - name: Debug
      debug:
          msg: "{{ message_processor_resp.stdout }}"
          
    - name: Notify failure
      fail:
        msg: "APIGEE MP ON SERVER {{ inventory_hostname }} IS UP AND REACHABLE"
      when: '"HTTP/1.1 200" not in message_processor_resp.stdout'

# Port 8998 validation for communication between router and message processors

    - name: Check open port 8998 on MP server1 on SWN01 for communication between router and message processors
      shell: nc -vz 10.65.188.30 8998
      register: MR11_port_8998

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 8998 ON 10.65.188.30 SERVER"
      when: '"Connected to 10.65.188.30:8998" not in MR11_port_8998.stderr'

    - name: Check open port 8998 on cassandra server2 SWN01 for communication between router and message processors
      shell: nc -vz 10.65.188.31 8998
      register: MR12_port_8998

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 8998 ON 10.65.188.31 SERVER"
      when: '"Connected to 10.65.188.31:8998" not in MR12_port_8998.stderr'

    - name: Check open port 8998 on cassandra server3 SWN01 for communication between router and message processors
      shell: nc -vz 10.65.188.32 8998
      register: MR13_port_8998

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 8998 ON 10.65.188.32 SERVER"
      when: '"Connected to 10.65.188.32:8998" not in MR13_port_8998.stderr'

    - name: Check open port 8998 on cassandra server1 DEN06 for communication between router and message processors
      shell: nc -vz 10.71.178.30 8998
      register: MR21_port_8998

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 8998 ON 10.71.178.30 SERVER"
      when: '"Connected to 10.71.178.30:8998" not in MR21_port_8998.stderr'

    - name: Check open port 8998 on cassandra server2 DEN06 for communication between router and message processors
      shell: nc -vz 10.71.178.31 8998
      register: MR22_port_8998

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 8998 ON 10.71.178.31 SERVER"
      when: '"Connected to 10.71.178.31:8998" not in MR22_port_8998.stderr'

    - name: Check open port 8998 on cassandra server3 DEN06 for communication between router and message processors
      shell: nc -vz 10.71.178.32 8998
      register: MR23_port_8998

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 8998 ON 10.71.178.32 SERVER"
      when: '"Connected to 10.71.178.32:8998" not in MR23_port_8998.stderr'

# Port 4528 validation on message processor for distributed cache and management calls

    - name: Check open port 4528 on MP server1 on SWN01 for distributed cache and management calls
      shell: nc -vz 10.65.188.30 4528
      register: MP11_port_4528

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4528 ON 10.65.188.30 SERVER"
      when: '"Connected to 10.65.188.30:4528" not in MP11_port_4528.stderr'

    - name: Check open port 4528 on cassandra server2 SWN01 for distributed cache and management calls
      shell: nc -vz 10.65.188.31 4528
      register: MP12_port_4528

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4528 ON 10.65.188.31 SERVER"
      when: '"Connected to 10.65.188.31:4528" not in MP12_port_4528.stderr'

    - name: Check open port 4528 on cassandra server3 SWN01 for distributed cache and management calls
      shell: nc -vz 10.65.188.32 4528
      register: MP13_port_4528

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4528 ON 10.65.188.32 SERVER"
      when: '"Connected to 10.65.188.32:4528" not in MP13_port_4528.stderr'

    - name: Check open port 4528 on cassandra server1 DEN06 for distributed cache and management calls
      shell: nc -vz 10.71.178.30 4528
      register: MP21_port_4528

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4528 ON 10.71.178.30 SERVER"
      when: '"Connected to 10.71.178.30:4528" not in MP21_port_4528.stderr'

    - name: Check open port 4528 on cassandra server2 DEN06 for distributed cache and management calls
      shell: nc -vz 10.71.178.31 4528
      register: MP22_port_4528

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4528 ON 10.71.178.31 SERVER"
      when: '"Connected to 10.71.178.31:4528" not in MP22_port_4528.stderr'

    - name: Check open port 4528 on cassandra server3 DEN06 for distributed cache and management calls
      shell: nc -vz 10.71.178.32 4528
      register: MP23_port_4528

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4528 ON 10.71.178.32 SERVER"
      when: '"Connected to 10.71.178.32:4528" not in MP23_port_4528.stderr'

# Port 4527 validation on message router for distributed cache and management calls

    - name: Check open port 4527 on MP server1 on SWN01 for distributed cache and management calls
      shell: nc -vz 10.65.188.30 4527
      register: MR11_port_4527

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4527 ON 10.65.188.30 SERVER"
      when: '"Connected to 10.65.188.30:4527" not in MR11_port_4527.stderr'

    - name: Check open port 4527 on cassandra server2 SWN01 for distributed cache and management calls
      shell: nc -vz 10.65.188.31 4527
      register: MR12_port_4527

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4527 ON 10.65.188.31 SERVER"
      when: '"Connected to 10.65.188.31:4527" not in MR12_port_4527.stderr'

    - name: Check open port 4527 on cassandra server3 SWN01 for distributed cache and management calls
      shell: nc -vz 10.65.188.32 4527
      register: MR13_port_4527

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4527 ON 10.65.188.32 SERVER"
      when: '"Connected to 10.65.188.32:4527" not in MR13_port_4527.stderr'

    - name: Check open port 4527 on cassandra server1 DEN06 for distributed cache and management calls
      shell: nc -vz 10.71.178.30 4527
      register: MR21_port_4527

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4527 ON 10.71.178.30 SERVER"
      when: '"Connected to 10.71.178.30:4527" not in MR21_port_4527.stderr'

    - name: Check open port 4527 on cassandra server2 DEN06 for distributed cache and management calls
      shell: nc -vz 10.71.178.31 4527
      register: MR22_port_4527

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4527 ON 10.71.178.31 SERVER"
      when: '"Connected to 10.71.178.31:4527" not in MR22_port_4527.stderr'

    - name: Check open port 4527 on cassandra server3 DEN06 for distributed cache and management calls
      shell: nc -vz 10.71.178.32 4527
      register: MR23_port_4527

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4527 ON 10.71.178.32 SERVER"
      when: '"Connected to 10.71.178.32:4527" not in MR23_port_4527.stderr'

# Port 5672 validation for communication to qpid from message processors and routers

    - name: Check open port 5672 on QPID server1 on SWN01 for communication between router and message processors to qpid
      shell: nc -vz 10.65.188.26 5672
      register: QP11_port_5672

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 5672 ON 10.65.188.26 SERVER"
      when: '"Connected to 10.65.188.26:5672" not in QP11_port_5672.stderr'

    - name: Check open port 5672 on QPID server2 on SWN01 for communication between router and message processors to qpid
      shell: nc -vz 10.65.188.27 5672
      register: QP12_port_5672

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 5672 ON 10.65.188.27 SERVER"
      when: '"Connected to 10.65.188.27:5672" not in QP12_port_5672.stderr'

    - name: Check open port 5672 on QPID server1 on DEN06 for communication between router and message processors to qpid
      shell: nc -vz 10.71.178.26 5672
      register: QP21_port_5672

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 5672 ON 10.65.188.26 SERVER"
      when: '"Connected to 10.71.178.26:5672" not in QP21_port_5672.stderr'

    - name: Check open port 5672 on QPID server2 on DEN06 for communication between router and message processors to qpid
      shell: nc -vz 10.71.178.27 5672
      register: QP22_port_5672

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 5672 ON 10.65.188.27 SERVER"
      when: '"Connected to 10.71.178.27:5672" not in QP22_port_5672.stderr'
