---
# tasks file for ZooKeeper_Cassandra

- name: Create the /etc/security/limits.d/90-apigee-edge-limits.conf file
  file:  path=/etc/security/limits.d/90-apigee-edge-limits.conf state=touch mode=0644
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"
  become: true
  become_method: su
  become_user: root

- name: Update system limits on Cassandra and Message Processor nodes
  pam_limits:
            domain: "{{ item.domain }}"
            limit_type: "{{ item.limit_type }}"
            limit_item: "{{ item.limit_item }}"
            value: "{{ item.value }}"
  with_items:
            - { domain: '{{ apigeeUser }}', limit_type: 'soft', limit_item: 'memlock', value: 'unlimited' }
            - { domain: '{{ apigeeUser }}', limit_type: 'hard', limit_item: 'memlock', value: 'unlimited' }
            - { domain: '{{ apigeeUser }}', limit_type: 'soft', limit_item: 'nofile', value: '32768' }
            - { domain: '{{ apigeeUser }}', limit_type: 'hard', limit_item: 'nofile', value: '65536' }
            - { domain: '{{ apigeeUser }}', limit_type: 'soft', limit_item: 'as', value: 'unlimited' }
            - { domain: '{{ apigeeUser }}', limit_type: 'hard', limit_item: 'as', value: 'unlimited' }
  become: true
  become_method: su
  become_user: root

- name: Check if Cassandra is running
  shell: ps aux | grep apigee-cassandra  | grep -v grep
  ignore_errors: true
  register: cassandra_output
#- debug: 
#       msg: "{{cassandra_output.stdout}}"

- name: Check if Zookeeper is running
  shell: ps aux | grep apigee-zookeeper  | grep -v grep
  ignore_errors: true
  register: zookeeper_output
#- debug: 
#       msg: "{{zookeeper_output.stdout}}"

- name: Install the ZooKeeper and Cassandra
  shell: /opt/apigee/apigee-setup/bin/setup.sh -p ds -f {{ configFilePath }} 
  when: cassandra_output.stdout == "" or zookeeper_output.stdout == ""
  become: true
  become_method: su
  become_user: root

