---
# tasks file for setup-agent

  - name: Create a folder, using symbolic modes to set the permissions
    file:
      path: /tmp/newrelic
      state: directory
      owner: root
      group: root
      mode: 0775
      

  - name: Copy Out Config
    template:
      src: etc/newrelic-java-agent.yml
      dest: /tmp/newrelic/newrelic.yml
      owner: apigee
      group: apigee
      mode: 0644

  - name: Download New Relic java agent
    command: curl -o /tmp/newrelic/newrelic-java-5.7.0.zip  http://download.newrelic.com/newrelic/java-agent/newrelic-agent/5.7.0/newrelic-java-5.7.0.zip
    args:
      warn: False

  - name: Ensures newrelic-java-5.7.0.zip file Exists
    file: 
     path: /tmp/newrelic/newrelic-java-5.7.0.zip
     state: file


  - name: Extract New Relic Java Agent
    unarchive:  
      src: /tmp/newrelic/newrelic-java-5.7.0.zip
      dest: /opt/apigee
      remote_src: yes

  - name: Ensures newrelic.yml, newrelic.jar file Exists
    file: 
      path: /opt/apigee/newrelic/newrelic.yml
      state: file
    file: 
      path: /opt/apigee/newrelic/newrelic.jar
      state: file

  - name: Configure newrelic-java-5.7.0
    template: 
      src: etc/newrelic-java-agent.yml
      dest: /opt/apigee/newrelic/newrelic.yml      
      owner: apigee
      group: apigee
      mode: 0644
...