---
# Components Installation validation in QPID nodes
    - name: Check Qpid process status
      shell: /opt/apigee/apigee-service/bin/apigee-service apigee-qpidd status 
      ignore_errors: true
      register: qpid_status

    - name: Debug
      debug:
        msg: "{{ qpid_status.stderr }}"

    - name: Notify failure
      fail:
          msg: "APIGEE QPID HAS NOT STARTED ON {{ inventory_hostname }} SERVER"
      when: '"apigee-service: apigee-qpidd: OK" not in qpid_status.stderr'

    - name: Check Qpid server process status
      shell: /opt/apigee/apigee-service/bin/apigee-service edge-qpid-server status
      ignore_errors: true
      register: qpid_server_status

    - name: Debug
      debug:
        msg: "{{ qpid_server_status.stderr }}"

    - name: Notify failure
      fail:
          msg: "APIGEE QPID SERVER HAS NOT STARTED ON {{ inventory_hostname }} SERVER"
      when: '"apigee-service: edge-qpid-server: OK" not in qpid_server_status.stderr'

# Check servers response status

    - name: Check apigee servers response status
      raw: "curl -I http://{{ inventory_hostname }}:8083/v1/servers/self/reachable"
      register: apigee_resp
     
    - name: Debug
      debug:
          msg: "{{ apigee_resp.stdout }}"
          
    - name: Notify failure
      fail:
        msg: "APIGEE QPID SERVER {{ inventory_hostname }} IS REACHABLE"
      when: '"HTTP/1.1 200" not in apigee_resp.stdout'

# Port 4529 validation on QPID for distributed cache and management calls

    - name: Check open port 4529 on QPID server1 on SWN01 for distributed cache and management calls
      shell: nc -vz 10.65.188.26 4529
      register: QP11_port_4529

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4529 ON 10.65.188.26 SERVER"
      when: '"Connected to 10.65.188.26:4529" not in QP11_port_4529.stderr'

    - name: Check open port 4529 on QPID server2 on SWN01 for distributed cache and management calls
      shell: nc -vz 10.65.188.27 4529
      register: QP12_port_4529

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4529 ON 10.65.188.27 SERVER"
      when: '"Connected to 10.65.188.27:4529" not in QP12_port_4529.stderr'

    - name: Check open port 4529 on QPID server1 on DEN06 for distributed cache and management calls
      shell: nc -vz 10.71.178.26 4529
      register: QP21_port_4529

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4529 ON 10.71.178.26 SERVER"
      when: '"Connected to 10.71.178.26:4529" not in QP21_port_4529.stderr'

    - name: Check open port 4529 on QPID server2 on DEN06 for distributed cache and management calls
      shell: nc -vz 10.71.178.27 4529
      register: QP22_port_4529

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 4529 ON 10.71.178.27 SERVER"
      when: '"Connected to 10.71.178.27:4529" not in QP22_port_4529.stderr'

# Port 5672 validation on QPID for communication from the router and message processors to qpid

    - name: Check open port 5672 on QPID server1 on SWN01 for communication from the router and message processors to qpid
      shell: nc -vz 10.65.188.26 5672
      register: QP11_port_5672

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 5672 ON 10.65.188.26 SERVER"
      when: '"Connected to 10.65.188.26:5672" not in QP11_port_5672.stderr'

    - name: Check open port 5672 on QPID server2 on SWN01 for communication from the router and message processors to qpid
      shell: nc -vz 10.65.188.27 5672
      register: QP12_port_5672

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 5672 ON 10.65.188.27 SERVER"
      when: '"Connected to 10.65.188.27:5672" not in QP12_port_5672.stderr'

    - name: Check open port 5672 on QPID server1 on DEN06 for communication from the router and message processors to qpid
      shell: nc -vz 10.71.178.26 5672
      register: QP21_port_5672

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 5672 ON 10.71.178.26 SERVER"
      when: '"Connected to 10.71.178.26:5672" not in QP21_port_5672.stderr'

    - name: Check open port 5672 on QPID server2 on DEN06 for communication from the router and message processors to qpid
      shell: nc -vz 10.71.178.27 5672
      register: QP22_port_5672

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 5672 ON 10.71.178.27 SERVER"
      when: '"Connected to 10.71.178.27:5672" not in QP22_port_5672.stderr'

# Port 5432 validation on Postgres for communication from Qpid server to postgres

    - name: Check open port 5432 on Postgres server on SWN01 for communication from Qpid server to postgres
      shell: nc -vz 10.71.178.28 5432
      register: postgresql_master_5432

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 5432 ON 10.71.178.28SERVER"
      when: '"Connected to 10.71.178.28:5432" not in postgresql_master_5432.stderr'

    - name: Check open port 5432 on Postgres server on DEN06 for communication from Qpid server to postgres
      shell: nc -vz 10.65.188.28 5432
      register: postgresql_slave_5432

    - name: Notify failure
      fail:
        msg: "LISTENNING PORT 5432 ON 10.65.188.28 SERVER"
      when: '"Connected to 10.65.188.28:5432" not in postgresql_slave_5432.stderr'
      
   #- mail:
   # host: smtp.west.com
   #   port: 25
   #   username: aullah
   #  password: *************
   #  to: aullah@west.com
   #   subject: Jenkins-report
   #   body: 'In server {{ inventory_hostname }} QPID has been successfully Installed.'


  #- name: Send Email
  #  mail:
  #    subject: "STATUS: Jenkins Report"
  #    to: aullah@west.com
  #    body: "ERROR: QPID IS NOT RUNNIG ON {{ inventory_hostname }} SERVER"
  #   delegate_to: localhost
  #  when: status.stdout.find('start/running') == -1
